### ISSUE TITLE
Is there a way to reset admin password?

### ISSUE THREAD

**Issue by ADIOP55550** [ElTh0r0/preferendum#3]
I searched through config files but could not find any place where it can be done. Is there a way to do so or do I need to reinstall the whole app?

**Comment by ADIOP55550** [comment]
UPDATE: 
I have deleted the entry from the DB hoping that it would fix it - still cannot log in, even with default credentials

**Comment by ElTh0r0** [comment]
Hi ADIOP55550,
if you don't have a second administrator, you can only reset the password inside the database directly. Since there is no clear text password saved in the DB but only the password hash, you would need to restore the initial hash, which was inserted into the DB during the installation:
https://github.com/ElTh0r0/preferendum/blob/145a69ee04abfce1c2de46f332b7326cf457e8bb/src/Controller/InstalldbController.php#L146

**Comment by ADIOP55550** [comment]
It worked!

**Note:** I had to _**clear all my cookies**_ from the site and after executing (in PhpMyAdmin)
```sql
INSERT INTO `users` (`pollid`, `name`, `info`) VALUES
        (9999, "admin", "$2y$10$YW0XBpcu4RoiUR5tW/rImuChkO1h8LDyecm6F1/Cty5QhJrwP958e");
```
I was able to go to the admin login again and log in with L: `admin` P: `admin`

Thank you for support.

Closing
